# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20170207_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name_plural': 'pages'},
        ),
    ]
